// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EXm_eWLvpxrG6wDllCizzEKHTU0Oftc',
    appId: '1:992233222981:web:3fbb70ada22f087444842c',
    messagingSenderId: '992233222981',
    projectId: 'zolpo-24b88',
    authDomain: 'zolpo-24b88.firebaseapp.com',
    storageBucket: 'zolpo-24b88.firebasestorage.app',
    measurementId: 'G-TQL1VT970X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPyHozjQaAIOklbQEM1wkx-tNRVcGuVaw',
    appId: '1:992233222981:android:63607181749133d444842c',
    messagingSenderId: '992233222981',
    projectId: 'zolpo-24b88',
    storageBucket: 'zolpo-24b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBSbffkVUcO1YHbUiYa_jwo_zwq3suavc',
    appId: '1:992233222981:ios:de3d8f29a879095b44842c',
    messagingSenderId: '992233222981',
    projectId: 'zolpo-24b88',
    storageBucket: 'zolpo-24b88.firebasestorage.app',
    iosBundleId: 'com.example.zolpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBSbffkVUcO1YHbUiYa_jwo_zwq3suavc',
    appId: '1:992233222981:ios:de3d8f29a879095b44842c',
    messagingSenderId: '992233222981',
    projectId: 'zolpo-24b88',
    storageBucket: 'zolpo-24b88.firebasestorage.app',
    iosBundleId: 'com.example.zolpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EXm_eWLvpxrG6wDllCizzEKHTU0Oftc',
    appId: '1:992233222981:web:11e3d6bf0618fe2c44842c',
    messagingSenderId: '992233222981',
    projectId: 'zolpo-24b88',
    authDomain: 'zolpo-24b88.firebaseapp.com',
    storageBucket: 'zolpo-24b88.firebasestorage.app',
    measurementId: 'G-EYK4NJL4QN',
  );
}
